### ISSUE TITLE
update for pypi please

### ISSUE THREAD

**Issue by peircej** [cedrus-opensource/pyxid#11]
Would it be possible to update the pypi release?
  https://pypi.python.org/pypi/pyxid/

Right now anyone doing `pip install pyxid` gets a version from 2011 including several bugs that have been fixed. In PsychoPy I'm not planning on shipping versions of libs that I have to collect manually from github; only pypi installs will be included unless there's a good reason that these aren't possible

many thanks

**Comment by habboud** [comment]
PyPi has been up-to-date for a while now.
