### ISSUE TITLE
Cedrus/pyxid2 issue on Windows machine

### ISSUE THREAD

**Issue by wallenut** [cedrus-opensource/pyxid#16]
I'm using a response pad rb 840 model on a windows machine and have some code to detect the devices before trying to read the key inputs.

import pyxid2
devices = pyxid2.get_xid_devices()
device = devices[0]

However I get the error that the list Index is out of bounds since devices returns an empty list []. Of the 4 mode pins, I have the first one flipped up and 2-4 are in the down position. Also when I use the Xidon software, it is able to detect the response pad so I don't think this is a hardware issue. Can someone help point me to how I might fix this issue? When I plugged the usb in, there wasn't automatic driver set up so I did have to download drivers from the 'Support' tab link on the Cedrus site.

**Comment by cedrus** [comment]
When you say “I have the first one flipped up”, are you referring to the leftmost switch (no. 1)? If yes, that switch puts the RB-840 in keyboard mode, in which case neither Xidon or the pyxid2 can detect its presence. See [The Response Pad DIP Switches](https://cedrus.com/support/rb_series/tn1544_dip_switches.htm).

**Comment by wallenut** [comment]
Thanks, that fixed it!
