### ISSUE TITLE
ftd2xx Device Error - Response Pad not opened

### ISSUE THREAD

**Issue by wallenut** [cedrus-opensource/pyxid#17]
Hey there, I am using an RB 840 response pad with all switches flipped down. I have a test_response_pay.py script that simply looks like this:

```
import pyxid2
from multiprocessing import Process
import time

def test_process():

	devices = pyxid2.get_xid_devices()

	rb_pad = devices[0]

	while True:
		while not rb_pad.has_response():
			rb_pad.poll_for_response()
		response = rb_pad.get_next_response()
		print(response)
		
if __name__ == "__main__":
	p = Process(target=test_process)
	p.start()
	p.join()
```

And this works on a windows 10 laptop. On another windows machine however, with pyxid2 and ftd2xx and the FTDI drivers installed, I end up getting this error when running the test script on command prompt:

```
(lab-env) C:\Users\allenwang\Desktop>python test_response_pad.py
Process Process-1:
Traceback (most recent call last):
  File "E:\lab-env\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "E:\lab-env\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\allenwang\Desktop\test_response_pad.py", line 8, in test_process
    devices = pyxid2.get_xid_devices()
  File "E:\lab-env\lib\site-packages\pyxid2\__init__.py", line 13, in get_xid_devices
    com.open()
  File "E:\lab-env\lib\site-packages\pyxid2\internal.py", line 66, in open
    self.ftd2xx_con = ftd2xx.openEx(self.ftd2xx_intermediate)
  File "E:\lab-env\lib\site-packages\ftd2xx\ftd2xx.py", line 108, in openEx
    call_ft(_ft.FT_OpenEx, id_str, _ft.DWORD(flags), c.byref(h))
  File "E:\lab-env\lib\site-packages\ftd2xx\ftd2xx.py", line 44, in call_ft
    raise DeviceError(status)
ftd2xx.ftd2xx.DeviceError: DEVICE_NOT_OPENED
```

Can someone point me to where I could debug this issue?

**Comment by ematsakCedrus** [comment]
From what I can tell, it seems like everything is in order with the library itself.

Try downloading Xidon 2 from here: https://cedrus.com/support/xid/xidon.htm and see if it picks up the response pad.

It would rule out drivers as the source of the issue, since it also uses ftd2xx.

**Comment by wallenut** [comment]
So the Xidon 2 is able to pick up and detect the response pad. I also took the conda environment I was using on a separate computer that worked and tried to copy it over but encountered the same DEVICE NOT OPENED error. If this means that the drivers and the pyxid/ftd2xx packages are not the source of the issue, what else could be contributing to this error?

**Comment by ematsakCedrus** [comment]
Try running this bit of code that just uses ftd2xx directly to communicate to the response pad. If this works for you, then it conclusively rules out the ftd2xx package as the source of the issue. If it works, the output should be something like this:

b'_xid0'
<ftd2xx.ftd2xx.FTD2XX object at 0x030244B0>

```
import ftd2xx

devs = ftd2xx.listDevices()

for d in devs:
    dev = ftd2xx.openEx(d)

    dev.setBaudRate(115200)
    dev.setDataCharacteristics(8, 0, 0)

    dev.setTimeouts(50, 50)
    dev.setUSBParameters(64,64)
    dev.setLatencyTimer(10)

    dev.purge()

    dev.write(b'_c1')
    print(dev.read(5))

    print(dev)

    dev.close()
```

**Comment by wallenut** [comment]
That bit of code did work and the output matched. The only other thing I can think of is that when I'm scanning for the xid device, I am doing so in a class that has been forked into its own Process. Within that class, the setup function looks like this:

```
def setup(self) -> None:
    devices = pyxid2.get_xid_devices()
    t = time.time()
    if len(devices):
        self.rb_pad = devices[self.idx if self.idx < len(devices) else 0]
        self.start_time = t
```

And the error I get is

```
41, in setup
    devices = pyxid2.get_xid_devices()
  File "C:\ProgramData\Anaconda3\envs\env\lib\site-packages\pyxid2\__init__.py", line 13, in get_xid_devices
    com.open()
  File "C:\ProgramData\Anaconda3\envs\env\lib\site-packages\pyxid2\internal.py", line 66, in open
    self.ftd2xx_con = ftd2xx.openEx(self.ftd2xx_intermediate)
  File "C:\ProgramData\Anaconda3\envs\env\lib\site-packages\ftd2xx\ftd2xx.py", line 108, in openEx
    call_ft(_ft.FT_OpenEx, id_str, _ft.DWORD(flags), c.byref(h))
  File "C:\ProgramData\Anaconda3\envs\env\lib\site-packages\ftd2xx\ftd2xx.py", line 44, in call_ft
    raise DeviceError(status)
ftd2xx.ftd2xx.DeviceError: DEVICE_NOT_OPENED
```

**Comment by ematsakCedrus** [comment]
I'm running out of things to suggest here. It's possible that doing this in a separate process is causing the problem, but then I'm not sure why it would only be the one machine.

One last thing I can think of to try is to try replacing that get_xid_devices() code snippet with the ftd2xx code from my last comment. If it works, that would completely narrow it down to a bug in pyxid. 

However, even at that point I'm not entirely sure what I could do. I haven't been able to reproduce this issue on my end, which makes it hard to fix.

**Comment by wallenut** [comment]
Thanks for your timely responses! The ftd2xx code works when I swap it in for the pyxid2 snippet. All I am trying to do is pick one of the Response pads and read the key inputs. The pyxid2 library would output it in JSON. Is it possible for me to do this without having to use the pyxid2 library and just with ftd2xx?

**Comment by habboud** [comment]
I think that the next best step would be to do screen sharing. Please send us an email via 

   https://cedrus.com/send_email.htm

with attention to Eugene and indicate your geographical area (so we know the time difference with California), and he’ll contact you,

**Comment by vin-turnier** [comment]
@wallenut This issue that you are having might be because you are running it in a separate process `Process`. Try using a `Thread` instead. I am not quite sure why `Process` does not work with ftd2xx. That is something I am currently investigating

**Comment by LMBooth** [comment]
Hi @ematsakCedrus , @wallenut , @habboud  and @vin-turnier I seem to be having a similar problem and am also trying to use the ftd2xx library in separate processes, i am able to run it in my main process, close the device, then reopen in a sub process, it seems that after trying to close the device in the subprocess i get a similar error as @wallenut, i don't suppose anyone has had any further experience?

**Comment by LMBooth** [comment]
Hi @ematsakCedrus , @wallenut , @habboud and @vin-turnier I seem to be having a similar problem and am also trying to use the ftd2xx library in separate processes, i am able to run it in my main process, close the device, then reopen in a sub process, it seems that after trying to close the device in the subprocess i get a similar error as @wallenut, i don't suppose anyone has had any further experience?

**Comment by habboud** [comment]
Please try updating to the latest version of pyxid2 and let us know if the issue is still there. We recently fixed a bug where pyxid2 was failing to find and open a Cedrus device when another USB device is connected that uses the same FTDI USB interface chip.
