### ISSUE TITLE
PsychoPy3 and pyxid

### ISSUE THREAD

**Issue by pradau** [cedrus-opensource/pyxid#19]
I've been struggling to get PsychoPy3 working with my old Cedrus controller (Lumina LSC-400B).
PsychoPy2 (1.90.0) had worked fine but after an upgrade of the OS (Vista to Win10) and Psychopy2 to 3, it no longer worked. More detail in this [post](https://discourse.psychopy.org/t/trying-to-use-v3-2-with-cedrus-button-box-error-unable-to-find-d2xx-dll-please-make-sure-ftd2xx-dll-or-ftd2xx64-dll-is-in-the-path/10085) at the PsychoPy forum.

My question: is my LSC-400B supposed to be compatible with the current pyxid module?  Even though I'm not using a USB-to-serial converter?  To me it appears that I'm supposed to be using a converter and that's why the dependency on the ftd2xx module exists.
And since I've determined that older versions of pyxid (without the ftd dependency) do work, then can you point to a pyxid release that you'd recommend me to use?

Thank you!

**Comment by habboud** [comment]
Please see answer [on this page](https://discourse.psychopy.org/t/trying-to-use-v3-2-with-cedrus-button-box-error-unable-to-find-d2xx-dll-please-make-sure-ftd2xx-dll-or-ftd2xx64-dll-is-in-the-path/10085).
