### ISSUE TITLE
response pad stops responding from time to time

### ISSUE THREAD

**Issue by achetverikov** [cedrus-opensource/pyxid#4]
I use RB830 with pyxid and psychopy. Most of the time everything goes fine, but occasionally response pad simply stops responding. It happens even in the demo script from the readme (I just added printing of the response). It is not (i hope) the hardware problem as I have 2 RB830 and both of them have this issue.

**Comment by habboud** [comment]
pyxid has been superseded by pyxid2. There are no bugs in pyxid2 that we’re aware of.

**Comment by teich047** [comment]
> pyxid has been superseded by pyxid2. There are no bugs in pyxid2 that we’re aware of.

Hi there. Our group is experiencing (seemingly) this exact issue using pyxid2 with RB-740. We have the psychopy-cedrus package installed (0.1.0), and are running v2024.2.4 of PsychoPy.
