### ISSUE TITLE
StimTracker.set_pulse_duration crashes

### ISSUE THREAD

**Issue by jacob-lee** [cedrus-opensource/pyxid#9]
Calling set_pulse_duration on a StimTracker object with value above approximately 400 (try 500), causes it to crash:

 File "cycle_all_lines.py", line 38, in <module>
    s.set_pulse_duration(500)
  File "build/bdist.macosx-10.10-x86_64/egg/pyxid/pyxid_impl.py", line 221, in set_pulse_duration
  File "build/bdist.macosx-10.10-x86_64/egg/pyxid/internal.py", line 90, in send_xid_command
  File "build/bdist.macosx-10.10-x86_64/egg/pyxid/internal.py", line 115, in write
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf4 in position 2: ordinal not in range(128)

**Comment by ematsakCedrus** [comment]
Hi, Jacob!

This was fixed earlier today on the master branch in 4243c5cd6aae608.

The bug was introduced in a patch aimed at improving Python3 compatibility. The change interfered with the XID command for setting pulse duration on a StimTracker for certain duration values, but it should work correctly now.

**Comment by jacob-lee** [comment]
Ah! Thanks! I was about to submit a pull request for my own patch this
evening; I opted to use byte arrays instead, which pySerial accepts, and I
find a bit less opaque for this sort of thing.

Thanks again.

Regards,

Jacob

**Comment by ematsakCedrus** [comment]
We considered byte arrays as well, but ultimately went with the more compact patch that worked for both python 2 and 3. Have you tested your patch with both?

**Comment by jacob-lee** [comment]
No, hadn't gotten that far; I think your decision was better than mine,
since bytearrays were only introduced in 2.6.
